dist: xenial

language: go

go:
- 1.12.x

git:
  depth: 1

before_deploy:
- mv ./content/resources/src/hello-world.code ./content/resources/src/hello-world.go
- mv ./content/resources/src/variables.code ./content/resources/src/variables.go
- mv ./content/resources/src/types.code ./content/resources/src/types.go
- mv ./content/resources/src/operators.code ./content/resources/src/operators.go
- mv ./content/resources/src/functions.code ./content/resources/src/functions.go

deploy:
  provider: gae
  keyfile: client-secret.json
  project: shockbyte-golang-workshop