dist: xenial

language: go

go:
- 1.12.x

git:
  depth: 1

before_install:
- mv ./resources/src/hello-world.go ./resources/src/hello-world.code
- mv ./resources/src/variables.go ./resources/src/variables.code
- mv ./resources/src/types.go ./resources/src/types.code
- mv ./resources/src/functions.go ./resources/src/operators.code
- mv ./resources/src/functions.go ./resources/src/operators.code
- openssl aes-256-cbc -K $encrypted_5b91aa6414c7_key -iv $encrypted_5b91aa6414c7_iv
  -in client-secret.json.enc -out client-secret.json -d

before_DEPLOY:
- mv ./resources/src/hello-world.code ./resources/src/hello-world.go
- mv ./resources/src/variables.code ./resources/src/variables.go
- mv ./resources/src/types.code ./resources/src/types.go
- mv ./resources/src/functions.code ./resources/src/operators.go
- mv ./resources/src/functions.code ./resources/src/operators.go

deploy:
  provider: gae
  keyfile: client-secret.json
  project: shockbyte-go-workshop
