dist: xenial

language: go

go:
- 1.12.x

git:
  depth: 1

before_install:
- mv ./content/resources/src/hello-world.go ./content/resources/src/hello-world.code
- mv ./content/resources/src/variables.go ./content/resources/src/variables.code
- mv ./content/resources/src/types.go ./content/resources/src/types.code
- mv ./content/resources/src/operators.go ./content/resources/src/operators.code
- mv ./content/resources/src/functions.go ./content/resources/src/functions.code
- mv ./content/resources/src/if.go ./content/resources/src/if.code
- mv ./content/resources/src/switch.go ./content/resources/src/switch.code
- mv ./content/resources/src/for-simple.go ./content/resources/src/for-simple.code
- mv ./content/resources/src/for-simpleBreak.go ./content/resources/src/for-simpleBreak.code
- mv ./content/resources/src/for-simpleContinue.go ./content/resources/src/for-simpleContinue.code
- mv ./content/resources/src/for-printTower.go ./content/resources/src/for-printTower.code
- mv ./content/resources/src/arrays.go ./content/resources/src/arrays.code
- mv ./content/resources/src/arrays-range.go ./content/resources/src/arrays-range.code
- mv ./content/resources/src/arrays-value-type.go ./content/resources/src/arrays-value-type.code
- mv ./content/resources/src/arrays-slices.go ./content/resources/src/arrays-slices.code
- mv ./content/resources/src/files.go ./content/resources/src/files.code
- mv ./content/resources/src/maps.go ./content/resources/src/maps.code
- mv ./content/resources/src/cmdline-args.go ./content/resources/src/cmdline-args.code
- mv ./content/resources/src/cmdline-flags.go ./content/resources/src/cmdline-flags.code
- mv ./content/resources/src/cmdline-env.go ./content/resources/src/cmdline-env.code
- mv ./content/resources/src/test.go ./content/resources/src/test.code
- mv ./content/resources/src/test-benchmark.go ./content/resources/src/test-benchmark.code
- mv ./content/resources/src/test-benchmark-wrong.go ./content/resources/src/test-benchmark-wrong.code
- mv ./content/resources/src/test-example.go ./content/resources/src/test-example.code
- mv ./content/resources/src/structs.go ./content/resources/src/structs.code
- mv ./content/resources/src/structs-nested.go ./content/resources/src/structs-nested.code
- mv ./content/resources/src/structs-methods.go ./content/resources/src/structs-methods.code
- mv ./content/resources/src/structs-pointers.go ./content/resources/src/structs-pointers.code
- openssl aes-256-cbc -K $encrypted_5b91aa6414c7_key -iv $encrypted_5b91aa6414c7_iv
  -in client-secret.json.enc -out client-secret.json -d

before_deploy:
- mv ./content/resources/src/hello-world.code ./content/resources/src/hello-world.go
- mv ./content/resources/src/variables.code ./content/resources/src/variables.go
- mv ./content/resources/src/types.code ./content/resources/src/types.go
- mv ./content/resources/src/operators.code ./content/resources/src/operators.go
- mv ./content/resources/src/functions.code ./content/resources/src/functions.go
- mv ./content/resources/src/if.code ./content/resources/src/if.go
- mv ./content/resources/src/switch.code ./content/resources/src/switch.go
- mv ./content/resources/src/for-simple.code ./content/resources/src/for-simple.go
- mv ./content/resources/src/for-simpleBreak.code ./content/resources/src/for-simpleBreak.go
- mv ./content/resources/src/for-simpleContinue.code ./content/resources/src/for-simpleContinue.go
- mv ./content/resources/src/for-printTower.code ./content/resources/src/for-printTower.go
- mv ./content/resources/src/arrays.code ./content/resources/src/arrays.go
- mv ./content/resources/src/arrays-range.code ./content/resources/src/arrays-range.go
- mv ./content/resources/src/arrays-value-type.code ./content/resources/src/arrays-value-type.go
- mv ./content/resources/src/arrays-slices.code ./content/resources/src/arrays-slices.go
- mv ./content/resources/src/files.code ./content/resources/src/files.go
- mv ./content/resources/src/cmdline-args.code ./content/resources/src/cmdline-args.go
- mv ./content/resources/src/cmdline-flags.code ./content/resources/src/cmdline-flags.go
- mv ./content/resources/src/cmdline-env.code ./content/resources/src/cmdline-env.go
- mv ./content/resources/src/test.code ./content/resources/src/test.go
- mv ./content/resources/src/test-benchmark.code ./content/resources/src/test-benchmark.go
- mv ./content/resources/src/test-benchmark-wrong.code ./content/resources/src/test-benchmark-wrong.go
- mv ./content/resources/src/test-example.code ./content/resources/src/test-example.go
- mv ./content/resources/src/structs.code ./content/resources/src/structs.go
- mv ./content/resources/src/structs-nested.code ./content/resources/src/structs-nested.go
- mv ./content/resources/src/structs-methods.code ./content/resources/src/structs-methods.go
- mv ./content/resources/src/structs-pointers.code ./content/resources/src/structs-pointers.go

deploy:
  provider: gae
  keyfile: client-secret.json
  project: golang-workshop-decks